version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: shaher
      MYSQL_DATABASE: newsfeed_db
      MYSQL_USER: shaher
      MYSQL_PASSWORD: shaher
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flask:
    build: ./flask_app
    container_name: flask_app_container
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USERNAME: shaher
      DB_PASSWORD: shaher
      DB_NAME: newsfeed_db
    depends_on:
      - mysql
    volumes:
      - ./flask_app:/app
    command: flask run --host=0.0.0.0 --port=5000

volumes:
  mysql_data:
